secret:
    top: ENC[AES256_GCM,data:wrdA0zafa+s=,iv:uN967XJVz57YZUfAS4pevr2+bsvp8/5QGHxdACY+VoM=,tag:3vMs+kA4dY3NP/EY+lIgnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://uk-dev-keyvault.vault.azure.net
        name: uk-dev-sops-tyk
        version: 3933f9208f0f4192828db88385a5b3a3
        created_at: '2020-08-24T17:01:22Z'
        enc: Oq39G_xh5B4khzQc_Gou6_bYfehL0pYFttrykFV0Oe9kjZiw2P8VtDqm8irmGCqe9ihcnLGWGsIO1rgvNNEQIxDWczbfXnlKYjduS1vywD_qhN23Lfb4oSB23GWTmDs5G93oVFNg8bKj6nKOhEhAX1i9GXt-t3_EdB_U-NK-wx6wLIhYECrTJpZik3BWlEGA5Qdz1QsNVDRUb-Yj0e0TBqGXu7dcmBlSB72d9-eFBGcTf23XtFxFPBOW913mgA9RQbv7BEGTrQjVWjRiRfCj6ILh5w3lmNNd4s_cb48ryFnhmYgZWS8Vrs_gJDwx8m5yvefrLS5rSHzDlU3hKyd5Fg
    lastmodified: '2020-08-24T17:01:41Z'
    mac: ENC[AES256_GCM,data:hCZFts/j2LKS7wwLjCqCycmpD75XTrkw3ah+J7HqlSKvcch72qXap9UoRpRxueJ0+hWBIZs/TDwQ3l9PU4O6HS4dfPjzCk4TShzLnSXEkLFMQLpDYAtIFqZDn4xQrnTWHnyuccDPShiscXRV6htYQHuVZRvcs8voAR5byMfLf78=,iv:18POZavbd5frVZjR/H80mIvftFfgRccUnFAwYL6FMg4=,tag:uLNQlRqSj8Px15yjrFD7Fg==,type:str]
    pgp:
    -   created_at: '2020-08-24T17:01:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQf+NNKmqhftWaief2GIXbtDstRkhvvR8LCyqVFDWspLHb/2
            xAwt1bSEZVyFXWtMRGXfVLGvmtOEhyPcwz/KcicsY9D7wnHEvK0DhWYVmtG8Wxbl
            qZaM1ZuPBxwM6Mv9+1WiHJWKNRevupVJKe0T7ZOi9SqVGmIw0JunJO3i18Z4Gijj
            KTO6Z+tJHtzMQ27x5MbGsuRZTEZZMRqzMe53RVJTOJgaGd9hIMG53eaw6JizItf/
            Rsc7HxSO8E0s/33Ig8t6sf2cLiNDb/zNE9SakrU3tm+wIrGQXi5PUc5CDebr3n9n
            SF5jcMEOphhts69p95VGxLDXhozy3NzaJ3gXN7ahjdJcAcJ39+vCq30V9srEVXhf
            sAVYJ0qmA2Xtsv/3f4P4jtdMGWhdJKS7TwGnYValhCC3UGQCmJ1MEPFb9EhrBpC1
            TIigd6OUFKJIfyP71RtYjC64xUc1D9EuIOPOFJg=
            =2E3V
            -----END PGP MESSAGE-----
        fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.5.0
